const express = require('express');

const router = express.Router();

function scoreTicket(ticket) {
  const text = [ticket.subject, ticket.latest_message].join(' ').toLowerCase();
  if (/(urgent|down|cannot|error|failed|immediately)/.test(text)) {
    return {
      matched: true,
      matches: [
        {
          id: 101,
          title: 'Urgent outage response playbook',
          category: 'incident',
          confidence: 0.91,
          answer: 'Acknowledge the outage, collect exact error details, and escalate immediately.'
        }
      ]
    };
  }

  if (/(invoice|billing|charge|payment|renewal)/.test(text)) {
    return {
      matched: true,
      matches: [
        {
          id: 202,
          title: 'Billing follow-up checklist',
          category: 'finance',
          confidence: 0.82,
          answer: 'Verify the invoice details, confirm account ownership, and route to billing ops.'
        }
      ]
    };
  }

  return { matched: false, matches: [] };
}

router.post('/qa-match', (req, res) => {
  const ticket = req.body || {};
  res.json(scoreTicket(ticket));
});

router.get('/supportdesk/attachments/:ticketId', (req, res) => {
  res.json({
    ticketId: req.params.ticketId,
    messages: []
  });
});

router.post('/supportdesk/test-ticket', (req, res) => {
  res.json({
    ok: true,
    upstream_status: 200,
    id: `demo-${Date.now()}`,
    received: req.body || {}
  });
});

router.post('/vision/analyze-ticket', (req, res) => {
  const messages = Array.isArray(req.body && req.body.messages) ? req.body.messages : [];
  let imageCount = 0;
  messages.forEach((message) => {
    const attachments = Array.isArray(message.attachments) ? message.attachments : [];
    imageCount += attachments.filter((attachment) => attachment && attachment.is_image).length;
  });

  res.json({
    images_analyzed: imageCount,
    analyses: []
  });
});

router.post('/gemini/chat', (req, res) => {
  const response = {
    ok: true,
    summary: 'Demo response generated by the local AI workflow scaffold.',
    action: 'review',
    priority: 'normal'
  };

  res.json({
    parsed: response,
    content: JSON.stringify(response)
  });
});

module.exports = router;
